### ISSUE TITLE
Decoded strings seem to be in reverse order

### ISSUE THREAD

**Issue by ftkurt** [soaxelbrooke/python-bpe#1]
Hi there, 

I really appreciate your work, and I am currently using this for my thesis, but I run across somthing as follows, which I think might be a bug:

![image](https://user-images.githubusercontent.com/5957317/33517905-45f46610-d79d-11e7-8865-0cd4bd75b4e5.png)
The tokens seem to be in reverse order:

Examples:
* bastan --> an bas
* duygu --> u duyg
* sömürüsü --> s s ömürüü

I am not sure if this is expected output. But something seems to be wrong.

**Comment by mwufi** [comment]
I just ran the snippet in the README, and didn't get the commented results?

Instead, I get:
```
['__sow', '__unk', '__unk', 'z', 'z', '__unk', '__unk', '__unk', '__eow', '__sow', ':', '__eow', '__sow', '__unk', '__unk', '__eow', '__sow', '__unk', '__unk', '__unk', '__unk', '__eow', '__sow', "'", '__eow', 't', '__sow', '__unk', '__unk', '__unk', '__unk', '__eow', '__sow', '?', '__eow', '__sow', '__unk', '__unk', '__unk', '__unk', '__unk', '__unk', '__unk', '__unk', '__unk', '__unk', '__unk', '__unk', '__unk', '__eow', '__sow', '!', '__eow']
[25, 1, 1, 29, 29, 1, 1, 1, 24, 25, 36, 24, 25, 1, 1, 24, 25, 1, 1, 1, 1, 24, 25, 28, 24, 3, 25, 1, 1, 1, 1, 24, 25, 30, 24, 25, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 24, 25, 33, 24]
__unk __unk __unk __unk __unk zz : __unk __unk __unk __unk __unk __unk ' t __unk __unk __unk __unk ? __unk __unk __unk __unk __unk __unk __unk __unk __unk __unk __unk __unk __unk !
```

**Comment by soaxelbrooke** [comment]
Hey there!  Thank you for creating this issue and sorry it took me so long to respond - I had this github repo configured wrong.  I'll check it out!

**Comment by ftkurt** [comment]
Hey @soaxelbrooke,

Thank you for the response. I tried again, but I am still getting the same output. I am attaching the corpus (a pickle in a zip) and adding some sample code below.

```
import pickle
from bpe import Encoder
with open("corpus.pickle","rb") as f:
    corpus = pickle.load(f).split("\n")

bpe_1k = Encoder(1000, ngram_max=10)
bpe_1k.fit(corpus)
print(next(bpe_1k.inverse_transform(bpe_1k.transform(["bastan"]))))
print(next(bpe_1k.inverse_transform(bpe_1k.transform(["duygu"]))))
print(next(bpe_1k.inverse_transform(bpe_1k.transform(["sömürüsü"]))))
```

The output should be as follows:

> an bast
> u duyg
> s s ömürüü

[corpus.zip](https://github.com/soaxelbrooke/python-bpe/files/1977751/corpus.zip)

**Comment by ftkurt** [comment]
Yes, it is fixed now. Great job!
