### ISSUE TITLE
Please consider adding a license

### ISSUE THREAD

**Issue by soldni** [soaxelbrooke/python-bpe#4]
Hello!

First of all, thank you so much for making this repository public! It would be great if you could attach a license to this project, so that this project can be used without violating any copyright issues. Otherwise, in absence of a license, this work is "[under exclusive copyright by default.](https://choosealicense.com/no-permission/)" In the past, I've used [Choose A License](https://choosealicense.com/), a website put together by GitHub, to decide with license to attach to my project.

Thank you!

-Luca

**Comment by soaxelbrooke** [comment]
Thanks for creating this issue, I didn't realize I had never added a license! I'll add a file specifying its license immediately.
