### ISSUE TITLE
Is it possible to apply BPE without SOW/EOW tokens?

### ISSUE THREAD

**Issue by universome** [soaxelbrooke/python-bpe#7]
It feels like using SOW/BOW will be consuming in terms of memory during training (sequences will become considerably longer, especially when vocab is large and there is not much BPEs). Does it give any improvements in score?

Btw, are you planning to put the lib on pypi?

**Comment by soaxelbrooke** [comment]
Hey @universome! I had planned on putting it on PyPI eventually, but then forgot to - definitely something I'd like to do in the near future.

About performance, I'd suggest testing on your own tasks to see what the memory and performance impact is.  Depending on your vocab parameters, most data should be picked up by the word tokenizer, and only words outside that vocab have SOW/EOW tokens around them, lowering their impact.

**Comment by soaxelbrooke** [comment]
Now that its up on PyPI, I'll close this.

https://pypi.org/project/bpe/
